name: CI Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * SUN'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: ubuntu-20.04, ruby: '3.1' }
        - { os: macos-12.2, ruby: '3.1' }
        - { os: windows-2019, ruby: '3.1' }
    name: test ${{ matrix.os }} ${{ matrix.ruby }} ${{ matrix.backend }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install Dependencies
        run: |
            gem install bundler
            bundle install --jobs 4 --retry 3
      - name: Test
        run: rake test
